spring:
  application:
    name: service-registry

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

eureka:
  server:
    enable-self-preservation: true