version: "3.9"

networks:
  vimodernization-net:
    external: true

services:

  # ---------------- SERVICE REGISTRY ----------------
  service-registry:
    build: ./service-registry
    image: service-registry:1.0
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - vimodernization-net
    environment:
      SPRING_PROFILES_ACTIVE: uat
      # OpenTelemetry Java Agent
      JAVA_TOOL_OPTIONS: -javaagent:/otel/opentelemetry-javaagent.jar

      # SigNoz internal OTEL collector (gRPC 4317)
      OTEL_EXPORTER_OTLP_ENDPOINT: http://signoz-otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc

      OTEL_SERVICE_NAME: service-registry
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
    volumes:
      - /home/akshay/Project Documents/DKYC_sammer/property_files:/app/config/propertyfiles
      - /home/akshay/Desktop/docker/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar

  # ---------------- API GATEWAY ----------------
  api-gateway:
    build: ./api-gateway
    image: api-gateway:1.0
    container_name: api-gateway
    ports:
      - "9090:9090"
    networks:
      - vimodernization-net
    depends_on:
      - service-registry
    environment:
      SPRING_PROFILES_ACTIVE: uat

      # OpenTelemetry Java Agent
      JAVA_TOOL_OPTIONS: -javaagent:/otel/opentelemetry-javaagent.jar

      # SigNoz internal OTEL collector (gRPC 4317)
      OTEL_EXPORTER_OTLP_ENDPOINT: http://signoz-otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc

      OTEL_SERVICE_NAME: api-gateway
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp


    volumes:
      - /home/akshay/Project Documents/DKYC_sammer/property_files:/app/config/propertyfiles
      - /home/akshay/Desktop/docker/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar

  # ---------------- LOGIN SERVICE ----------------
  login-service:
    build: ./login-service
    image: login-service:1.0
    container_name: login-service
    ports:
      - "9091:9091"
    networks:
      - vimodernization-net
    depends_on:
      - service-registry
    environment:
      SPRING_PROFILES_ACTIVE: uat

      # OpenTelemetry Java Agent
      JAVA_TOOL_OPTIONS: -javaagent:/otel/opentelemetry-javaagent.jar

      # SigNoz internal OTEL collector (gRPC 4317)
      OTEL_EXPORTER_OTLP_ENDPOINT: http://signoz-otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc

      OTEL_SERVICE_NAME: login-service
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp


    volumes:
      - /home/akshay/Project Documents/DKYC_sammer/property_files:/app/config/propertyfiles
      - /home/akshay/Desktop/docker/opentelemetry-javaagent.jar:/otel/opentelemetry-javaagent.jar


  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: vodafone_keycloak
    ports:
      - "8080:8080"
    networks:
      - vimodernization-net

    volumes:
      - /home/akshay/Desktop/ojdbc11.jar:/opt/keycloak/providers/ojdbc11.jar
      - /home/akshay/Desktop/docker/keycloak-mobile-auth-spi-1.0.0.jar:/opt/keycloak/providers/keycloak-mobile-auth-spi-1.0.0.jar

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: oracle
      KC_DB_URL: jdbc:oracle:thin:@10.1.1.207:1521:orcl
      KC_DB_USERNAME: vodafone_ekyc_keycloak
      KC_DB_PASSWORD: welcome

    command: [ "start-dev" ]



