server:
  port: 9090


spring:
  redis:
    host: redis
    port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.31.1.199:8080/realms/master

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
