server:
  port: 9091

propertyFiles: config/local/propertyFilePaths.yml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


keycloak:
  # -----------------------------
  # PRE-LOGIN TOKEN (existing)
  # -----------------------------
  token:
    url: http://localhost:8080/realms/vodafone/protocol/openid-connect/token

  client:
    id: vconnect-app
    secret: NkQGc4WoQqfTISbNLVjL8EBJzsa6JAAG


  # -----------------------------
  # ADMIN / USER MANAGEMENT
  # -----------------------------
  auth-server-url: http://localhost:8080
  realm: vodafone


  admin:
    client-id: vconnect-app
    client-secret: NkQGc4WoQqfTISbNLVjL8EBJzsa6JAAG



